# Check out Dependabot at: https://github.com/dependabot

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - ci
      - dependencies
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
